services:
  postgres:
    image: postgres:18
    container_name: news-etl-postgres
    environment:
      POSTGRES_DB: news
      POSTGRES_USER: news_user
      POSTGRES_PASSWORD: news_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  api:
    build: .
    container_name: news-etl-api
    ports:
      - "8000:8000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: news
      DB_USER: news_user
      DB_PASSWORD: news_password
    depends_on:
      - postgres

  postgres-test:
    image: postgres:18
    container_name: news-etl-postgres-test
    environment:
      POSTGRES_DB: news_test
      POSTGRES_USER: news_user
      POSTGRES_PASSWORD: news_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql

volumes:
  postgres_data:
  postgres_test_data:
